# list of pre-defined waypoints for the robot to navigate to
# each waypoint has a name and the coordinates (x, y, theta) in the map frame of reference
waypoints:
    - waypoint_1

waypoint_1:
    x: 0.57
    y: 4.1
    theta: -1.57

dropoff_waypoint:
    x: -1.3
    y: 1.4
    theta: 0.0
