# list of pre-defined waypoints for the robot to navigate to
# each waypoint has a name and the coordinates (x, y, theta) in the map frame of reference
waypoints:
    - waypoint_1
    - waypoint_2

waypoint_1:
    x: 0.0
    y: 0.0
    theta: 0.0

waypoint_2:
    x: 1.0
    y: 1.0
    theta: 0.0

dropoff_waypoint:
    x: 0.0
    y: 0.0
    theta: 0.0
