# picking objects: request
# empty request: search for object to pick and pick them
# int16 label # optionallt pick only objects of a specific class
---
# picking response
bool objects_remaining # whether there are some objects to pick in reachable range
---
# picking feedback
string status # text feedback about the ongoing process